lsi: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
url: https://sprinters.sh
exclude:
  - docker-compose.yml
  - Dockerfile
  - README.md
  - CNAME
  - "*.pdn"
  - "*.drawio"
